max_duration=320
lr=0.00005
pct_start=0.15
collar=0
total_max_overlaps=6000
total_steps=200000
hat=True
large=True
downsample=True
langdir=data/lang_bpe_5000
original_topo=False
beam_size=10
sort_strategy=start_time
num_spks=8
layer_norm=False
max_splices=10
max_splice_duration=50
max_unique=10
speaker_weight=1.0
overlap=0.0
min_overlap=0.0
drift=0.5
reverb=True
normalize_loudness=True
max_snr=30
allow_self_overlap=False
duration_increment=1e-05
no_overlap=True
