num_gpu=1
exp_name=exp3spk
max_duration=320
lr=0.0001
collar=64000
total_max_overlaps=4000
total_steps=100000
master_port=12354
hat=True
large=False
downsample=False
langdir=data/lang_bpe_5000
original_topo=False
beam_size=10
sort_strategy=start_time
num_spks=3
layer_norm=False
max_splices=4
max_splice_duration=30
max_unique=3
speaker_weight=1.0
overlap=0.4
drift=1.0
reverb=True
normalize_loudness=False

