max_duration=320
lr=0.0001
pct_start=0.15
collar=64000
total_max_overlaps=6000
total_steps=200000
hat=True
large=False
downsample=False
langdir=data/lang_bpe_5000
original_topo=False
beam_size=20
sort_strategy=speech_time
num_spks=3
layer_norm=False
max_splices=10
max_splice_duration=50
max_unique=4
speaker_weight=1.0
overlap=1.0
min_overlap=0.3
drift=0.5
reverb=False
normalize_loudness=False
max_snr=15
allow_self_overlap=False
