max_duration=320
lr=0.0001
collar=32000
total_max_overlaps=6000
total_steps=100000
hat=True
large=False
downsample=False
langdir=data/lang_bpe_5000
original_topo=False
beam_size=10
sort_strategy=start_time
num_spks=3
layer_norm=False
max_splices=10
max_splice_duration=60
max_unique=3
speaker_weight=1.0
overlap=1.0
drift=0.0
reverb=False
normalize_loudness=False
max_snr=30
allow_self_overlap=True
