#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=15
# run step 0 to step 5 by default
stage=0
stop_stage=5

# Note: This script just prepare the minimal requirements that needed by a
# transducer training with bpe units.
#
# If you want to use ngram or nnlm, please continue running prepare_lm.sh after
# you succeed running this script.
#
# This script also contains the steps to generate phone based units, but they
# will not run automatically, you can generate the phone based units by
# bash prepare.sh --stage -1 --stop-stage -1
# bash prepare.sh --stage 6 --stop-stage 6


# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/LibriSpeech
#      You can find BOOKS.TXT, test-clean, train-clean-360, etc, inside it.
#      You can download them from https://www.openslr.org/12
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#     - music
#     - noise
#     - speech
#
# lm directory is not necessary for transducer training with bpe units, but it
# is needed by phone based modeling, you can download it by running
# bash prepare.sh --stage -1 --stop-stage -1
# then you can see the following files in the directory.
#  - $dl_dir/lm
#      This directory contains the following files downloaded from
#       http://www.openslr.org/resources/11
#
#        - 3-gram.pruned.1e-7.arpa.gz
#        - 3-gram.pruned.1e-7.arpa
#        - 4-gram.arpa.gz
#        - 4-gram.arpa
#        - librispeech-vocab.txt
#        - librispeech-lexicon.txt
#        - librispeech-lm-norm.txt.gz

dl_dir=$PWD/download
lmdir=data/lm

. shared/parse_options.sh || exit 1

# vocab size for sentence piece models.
# It will generate data/lang_bpe_xxx,
# data/lang_bpe_yyy if the array contains xxx, yyy
vocab_size=5000

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

log "dl_dir: $dl_dir"

if [ $stage -le -1 ] && [ $stop_stage -ge -1 ]; then
  log "Stage -1: Download LM"
  mkdir -p $dl_dir/lm
  if [ ! -e $dl_dir/lm/.done ]; then
    ./local/download_lm.py --out-dir=$dl_dir/lm
    touch $dl_dir/lm/.done
  fi
fi

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"

  # If you have pre-downloaded it to /path/to/LibriSpeech,
  # you can create a symlink
  #
  #   ln -sfv /path/to/LibriSpeech $dl_dir/LibriSpeech
  #
  if [ ! -d $dl_dir/LibriSpeech/train-other-500 ]; then
    lhotse download librispeech --full $dl_dir
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare LibriSpeech manifest"
  # We assume that you have downloaded the LibriSpeech corpus
  # to $dl_dir/LibriSpeech
  mkdir -p data/manifests
  if [ ! -e data/manifests/.librispeech.done ]; then
    lhotse prepare librispeech -j $nj $dl_dir/LibriSpeech data/manifests
    touch data/manifests/.librispeech.done
  else
    echo "Skipping manifest prep."
    echo "Remove data/manifests/.librispeech.done to override."
  fi

  # Combine all of the 
  num_split=1
  split_dir=data/manifests/librispeech_train_split${num_split}
  # Handle the training set separately
  python local/split_cuts.py \
    ${split_dir} \
    --num-splits ${num_split} \
    --trim-to-supervisions \
    --recos data/manifests/librispeech_recordings_train*.jsonl.gz \
    --sups data/manifests/librispeech_supervisions_train*.jsonl.gz
 
  if [ $num_split -eq 1 ]; then
    cp ${split_dir}/cuts_0.jsonl.gz data/manifests/cuts_librispeech_train.jsonl.gz
  else  
    lhotse combine ${split_dir}/*.jsonl.gz data/manifests/cuts_librispeech_train.jsonl.gz
  fi

  # Shuffle cuts
  zcat data/manifests/cuts_librispeech_train.jsonl.gz |\
    shuf | gzip -c > data/manifests/cuts_librispeech_train_shuffled.jsonl.gz

  # Split into a few chunks (4)
  # We will use these to create overlapped speech examples on the fly, sampling
  # utterances from each chunk
  python local/split_cuts.py \
    data/manifests \
    --cuts data/manifests/cuts_librispeech_train_shuffled.jsonl.gz \
    --num-splits 4 \
    --oname librispeech_train_shuffled

  for ds in dev-clean dev-other test-clean test-other; do
    echo "Preparing ${ds} cuts ..."
    split_dir=data/manifests/librispeech_${ds}_split${num_split}
    # Handle the training set separately
    python local/split_cuts.py \
      ${split_dir} \
      --num-splits ${num_split} \
      --trim-to-supervisions \
      --recos data/manifests/librispeech_recordings_${ds}.jsonl.gz \
      --sups data/manifests/librispeech_supervisions_${ds}.jsonl.gz
   
  if [ $num_split -eq 1 ]; then
    cp ${split_dir}/cuts_0.jsonl.gz data/manifests/cuts_librispeech_${ds}.jsonl.gz
  else  
    lhotse combine ${split_dir}/*.jsonl.gz data/manifests/cuts_librispeech_${ds}.jsonl.gz
  fi

  done 
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 1: Prepare Audioset manifest"
  # We assume that you have downloaded the LibriSpeech corpus
  # to $dl_dir/LibriSpeech
  mkdir -p data/manifests
  if [ ! -e data/manifests/.audioset.done ]; then
    lhotse prepare audioset -j $nj $dl_dir/Audioset data/manifests
    touch data/manifests/.audioset.done
  else
    echo "Skipping manifest prep."
    echo "Remove data/manifests/.audioset.done to override."
  fi

  num_split=1
  # Add option to speed up with grid submission
  for ds in train eval; do
    echo "$ds"
  #for ds in eval; do
    split_dir=data/manifests/audioset_${ds}_split${num_split}
    # We need to normalize the text, create cuts, etc.
    # Make the cuts
    python local/split_cuts.py \
      ${split_dir} \
      --num-splits ${num_split} \
      --trim-to-supervisions \
      --recos data/manifests/audioset_recordings_${ds}.jsonl.gz \
      --sups data/manifests/audioset_supervisions_${ds}.jsonl.gz  

    # combine split cuts
    if [ $num_split -eq 1 ]; then
      cp ${split_dir}/cuts_0.jsonl.gz data/manifests/cuts_audioset_${ds}_trimmed.jsonl.gz 
    else
      lhotse combine $split_dir/cuts_*.jsonl.gz data/manifests/cuts_audioset_${ds}_trimmed.jsonl.gz
    fi    
    
    python local/map_sounds_to_ids.py \
      --num-jobs $nj \
      $dl_dir/Audioset/mid_to_display_name.tsv \
      data/manifests/cuts_audioset_${ds}_trimmed.jsonl.gz \
      data/manifests/cuts_audioset_${ds}_trimmed_mapped.jsonl.gz 
  done
  
  zcat data/manifests/cuts_audioset_train_trimmed_mapped.jsonl.gz |\
    shuf | gzip -c > data/manifests/cuts_audioset_train_shuffled.jsonl.gz

  python local/split_cuts.py \
    data/manifests \
    --num-splits 2 \
    --cuts data/manifests/cuts_audioset_eval_trimmed_mapped.jsonl.gz \
    --oname audioset_eval

  # Get one last eval set
  python local/split_cuts.py \
      data/manifests/audioset_eval_whole \
      --num-splits 2 \
      --recos data/manifests/audioset_recordings_eval.jsonl.gz \
      --sups data/manifests/audioset_supervisions_eval.jsonl.gz 

  for i in 1 2; do
    python local/map_sounds_to_ids.py \
      --num-jobs $j \
        $dl_dir/Audioset/mid_to_display_name.tsv \
        data/manifests/audioset_eval_whole/cuts_${i}.jsonl.gz \
        data/manifests/audioset_eval_whole/cuts_${i}_mapped.jsonl.gz
  done
fi


if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  # For each language get the text from the cuts
  mkdir -p ${lmdir}
  #for set in librispeech audioset; do
  for set in librispeech; do
    echo "Getting text from ${set} ..."
    python local/get_text_from_manifests.py \
      data/manifests/cuts_${set}_train_shuffled.jsonl.gz \
      ${lmdir}/transcript_${set}_words.txt;
  done
  
  cat ${lmdir}/transcript*_words.txt > ${lmdir}/transcript_all_words.txt
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  langdir=data/lang_bpe_${vocab_size}
  mkdir -p $langdir

  # Add special words to words.txt
  echo "<eps> 0" > $langdir/words.txt
  echo "!SIL 1" >> $langdir/words.txt
  echo "<UNK> 2" >> $langdir/words.txt
  
  cat ${lmdir}/transcript_*_words.txt | tr " " "\n" |\
     LC_ALL=C sort -u | awk '{print $0,NR+2}' >> ${langdir}/words.txt
  
  # Add remaining special word symbols expected by LM scripts.
  num_words=$(cat $langdir/words.txt | wc -l)
  echo "<s> ${num_words}" >> $langdir/words.txt
  num_words=$(cat $langdir/words.txt | wc -l)
  echo "</s> ${num_words}" >> $langdir/words.txt
  num_words=$(cat $langdir/words.txt | wc -l)
  echo "#0 ${num_words}" >> $langdir/words.txt
  
  nlsyms=( `cat <(echo "[SIL]") <(grep -o "\[[^][ ]*\]" ${lmdir}/transcript_all_words.txt) <(grep -o "<[^>< ]*>" ${lmdir}/transcript_all_words.txt) | LC_ALL=C sort -u` )
  nlsyms=$(echo ${nlsyms[@]} | tr " " ",")
  
  ./local/train_bpe_model.py \
    --lang-dir $langdir \
    --vocab-size $vocab_size \
    --transcript ${lmdir}/transcript_all_words.txt \
    --nlsyms ${nlsyms}
  
fi


